spring:
  servlet:
    multipart:
      enabled: false

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000

  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/18091?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/1809a

mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml
server:
  port: 8081
